name: Build and Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increase Patch Version
      run: |
        cd myapp
        mvn versions:set -DnewVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | awk -F. -v OFS=. '{$NF++;print}')
        mvn versions:commit

    - name: Compile with Maven
      run: cd myapp && mvn compile

    - name: Package with Maven
      run: cd myapp && mvn package
