name: Build and Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increase Patch Version
      run: |
        cd myapp
        # Get current version
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $current_version"
        # Increment the patch version
        new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
        echo "New version: $new_version"
        # Update the pom.xml with the new version
        mvn versions:set -DnewVersion=${new_version}-SNAPSHOT
        mvn versions:commit

    - name: Compile with Maven
      run: cd myapp && mvn compile

    - name: Package with Maven
      run: cd myapp && mvn package

    - name: Package with Maven
      run: java -cp target/myapp-1.0-SNAPSHOT.jar com.myapp.app.App
