name: Build and Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increase Patch Version
      run: |
        cd myapp
        git pull
        # Get current version
        current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Current version: $current_version"
        # Increment the patch version
        new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
        echo "New version: $new_version"
        # Update the pom.xml with the new version
        mvn versions:set -DnewVersion=${new_version}-SNAPSHOT -DgenerateBackupPoms=false
        mvn versions:commit
        # Verify the version change
        updated_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Updated version in pom.xml: $updated_version"

    - name: Commit and Push Version Change
      run: |
        cd myapp
        git config user.name "Dvir-Segal"
        git config user.email "dvirsegal96@gmail.com"
        git add pom.xml
        git commit -m "Bump version to ${new_version}-SNAPSHOT"
        git push


    - name: Compile with Maven
      run: cd myapp && mvn compile

    - name: Package with Maven
      run: cd myapp && mvn package

    - name: Print list
      run: cd myapp/target && java -cp myapp-1.0.1-SNAPSHOT.jar com.myapp.App

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: myapp/target/*.jar
