name: Build and Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Specify your Java version here
        distribution: 'adopt-openjdk'

    - name: Compile with Maven
      run: mvn compile

    - name: Package with Maven
      run: mvn package
