name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Increase Patch Version
      id: version
      run: |
        # Get current version
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # Extract the patch version
        patch=$(echo $version | awk -F. '{print $3}' | awk -F- '{print $1}')
        # Increment the patch version
        new_patch=$((patch + 1))
        # Set the new version
        new_version=$(echo $version | awk -F. '{print $1"."$2"."}'$new_patch)
        echo "New version: $new_version"
        echo "VERSION=$new_version" >> $GITHUB_ENV

    - name: Update Version in pom.xml
      run: |
        mvn versions:set -DnewVersion=${{ env.VERSION }}
        mvn versions:commit

    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: target/myapp-${{ env.VERSION }}.jar
