name: Build and Package

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Compile with Maven
      run: cd myapp && mvn compile

    - name: Package with Maven
      run: mvn package
